Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2020-05, with the labels that each got.

#668 ENH Add alt attribute for thumbnails
  sphinx_gallery/backreferences.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_backreferences.py
  sphinx_gallery/tests/test_full.py
Labels: enhancement

#670 DOC Clarify syntax.rst
  doc/syntax.rst
Labels: documentation

#680 ENH Add cross ref label to template module.rst
  doc/_templates/module.rst
  doc/configuration.rst
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/tinybuild/_templates/module.rst
  sphinx_gallery/tests/tinybuild/index.rst
Labels: enhancement

#682 Fix regex for numpy RandomState in test_full
  sphinx_gallery/tests/test_full.py
Labels: bug

#685 Sphinx directive to insert mini-galleries
  doc/_templates/module.rst
  doc/configuration.rst
  doc/reference.rst
  sphinx_gallery/backreferences.py
  sphinx_gallery/directives.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/tinybuild/_templates/module.rst
  sphinx_gallery/tests/tinybuild/minigallery.rst
Labels: enhancement

#687 ENH: Add support for FuncAnimation
  appveyor.yml
  doc/_static/theme_override.css
  doc/conf.py
  doc/configuration.rst
  examples/plot_8_animations.py
  sphinx_gallery/_static/gallery.css
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/scrapers.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/tinybuild/conf.py
  sphinx_gallery/tests/tinybuild/examples/plot_animation.py
  sphinx_gallery/utils.py
Labels: enhancement

#656 ENH: Use optipng when requested
  .circleci/config.yml
  .travis.yml
  README.rst
  doc/conf.py
  doc/configuration.rst
  doc/reference.rst
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/scrapers.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/tinybuild/conf.py
  sphinx_gallery/utils.py
Labels: enhancement

#690 ENH: Use Sphinx errors
  sphinx_gallery/backreferences.py
  sphinx_gallery/binder.py
  sphinx_gallery/docs_resolv.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/py_source_parser.py
  sphinx_gallery/scrapers.py
  sphinx_gallery/sorting.py
  sphinx_gallery/tests/conftest.py
  sphinx_gallery/tests/test_backreferences.py
  sphinx_gallery/tests/test_binder.py
  sphinx_gallery/tests/test_docs_resolv.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/test_gen_rst.py
  sphinx_gallery/tests/test_py_source_parser.py
  sphinx_gallery/tests/test_scrapers.py
  sphinx_gallery/tests/test_sorting.py
  sphinx_gallery/utils.py
Labels: enhancement

#696 Remove matplotlib agg warning
  sphinx_gallery/scrapers.py
  sphinx_gallery/tests/test_full.py
Labels: bug

#698 DOC remove mention of other builder types
  doc/getting_started.rst
Labels: documentation
