Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2020-03, with the labels that each got.

#619 BUG Fix test for new sphinx
  sphinx_gallery/tests/test_full.py
Labels: bug

#623 ENH: Add sub-classes for download links
  sphinx_gallery/downloads.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_gen_rst.py
Labels: enhancement

#625 ENH Add last cell config
  doc/configuration.rst
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/notebook.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/test_notebook.py
Labels: enhancement

#624 DOC use # %%
  doc/syntax.rst
  examples/no_output/plot_raise.py
  examples/plot_1_exp.py
  examples/plot_3_capture_repr.py
  examples/plot_4b_provide_thumbnail.py
  examples/plot_5_unicode_everywhere.py
  examples/plot_6_function_identifier.py
  sphinx_gallery/tests/reference_parse.txt
  tutorials/plot_parse.py
Labels: documentation

#629 BUG: Longer timeout on macOS
  sphinx_gallery/gen_rst.py
Labels: bug

#633 DOC minor update to release guide
  doc/maintainers.rst
Labels: documentation
