Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2020-04, with the labels that each got.

#638 ENH Allow backrefences_dir to be pathlib object
  doc/configuration.rst
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/tests/test_gen_gallery.py
Labels: enhancement

#641 MRG, ENH: Add Zenodo badge
  README.rst
Labels: enhancement

#647 Update pandas intersphinx url
  doc/conf.py
Labels: bug

#648 BUG: Fix CSS includes and add manifest check in CI
  MANIFEST.in
  continuous_integration/travis/install.sh
  continuous_integration/travis/test_script.sh
  dev-requirements.txt
  setup.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_backreferences.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/test_gen_rst.py
  sphinx_gallery/tests/test_py_source_parser.py
Labels: bug

#649 Update maintainers url in RELEASES.md
  RELEASES.md
Labels: documentation

#662 DOC Fix typos, clarify
  doc/configuration.rst
  doc/getting_started.rst
Labels: documentation

#667 DOC Note config comment removal in code only
  doc/configuration.rst
Labels: documentation

#663 ENH More informative 'alt' attribute for images
  examples/plot_1_exp.py
  sphinx_gallery/scrapers.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_scrapers.py
  sphinx_gallery/tests/tinybuild/examples/plot_matplotlib_alt.py
Labels: enhancement

#658 DOC Update html-noplot
  doc/configuration.rst
Labels: documentation
