Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2020-10, with the labels that each got.

#750 ENH: Add RST comments, read-only
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_gen_rst.py
Labels: enhancement

#752 ENH: Style HTML output like jupyter
  .circleci/config.yml
  appveyor.yml
  continuous_integration/travis/install.sh
  dev-requirements.txt
  doc/configuration.rst
  examples/plot_3_capture_repr.py
  setup.py
  sphinx_gallery/_static/gallery-rendered-html.css
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_gen_rst.py
  sphinx_gallery/tests/tinybuild/examples/plot_repr.py
Labels: enhancement

#754 DOC update link in projects_list
  doc/projects_list.rst
Labels: bug

#759 ENH: Add run_stale_examples config var
  .travis.yml
  doc/configuration.rst
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_full.py
Labels: enhancement

#762 DOC Standardise capitalisation of Sphinx-Gallery
  README.rst
  doc/advanced.rst
  doc/configuration.rst
  doc/getting_started.rst
  doc/index.rst
  examples/plot_9_plotly.py
  mayavi_examples/README.rst
  sphinx_gallery/backreferences.py
  sphinx_gallery/binder.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_backreferences.py
Labels: documentation

#763 DOC Amend run_stale_examples command in configuration.rst
  doc/configuration.rst
Labels: bug, documentation
