Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2023-03, with the labels that each got.

#1089 MAINT: Bump version to dev
  sphinx_gallery/__init__.py
Labels: maintenance

#1090 API: Remove deprecated mayavi support
  .circleci/config.yml
  .github_changelog_generator
  MANIFEST.in
  README.rst
  azure-pipelines.yml
  continuous_integration/azure/install.sh
  doc/Makefile
  doc/conf.py
  doc/configuration.rst
  doc/galleries.rst
  doc/maintainers.rst
  doc/make.bat
  mayavi_examples/README.rst
  mayavi_examples/plot_3d.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/scrapers.py
  sphinx_gallery/tests/test_scrapers.py
Labels: api

#1094 FIX: Add blank line at end of table of contents block
  sphinx_gallery/gen_gallery.py
Labels: bug

#1095 BUG: Fix bug with show_api_usage
  sphinx_gallery/gen_gallery.py
Labels: bug

#1097 FIX: Only ANSI sanitize non-HTML output
  sphinx_gallery/gen_rst.py
Labels: bug

#1099 Remove default '%matplotlib inline' line
  doc/configuration.rst
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/tests/test_notebook.py
Labels: bug

#1102 Avoid potentially changing the matplotlib backend when scraping
  sphinx_gallery/scrapers.py
Labels: bug

#1105 Fix JupyterLite URL with nested gallery folders
  sphinx_gallery/interactive_example.py
  sphinx_gallery/tests/test_interactive_example.py
Labels: bug

#1106 DOC Update JupyterLite doc after JupyterLite 0.1.0b19 release
  doc/configuration.rst
Labels: documentation

#1108 Fix thumbnail text formatting
  sphinx_gallery/gen_rst.py
Labels: bug

#1111 ENH: Add support for WebP
  doc/advanced.rst
  sphinx_gallery/scrapers.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/tinybuild/doc/conf.py
  sphinx_gallery/tests/tinybuild/examples/plot_webp.py
Labels: enhancement
