Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2023-11, with the labels that each got.

#1223 DOC: contributing guide
  doc/contribute.rst
  doc/index.rst
Labels: documentation

#1125 FEA Add examples recommender system
  continuous_integration/install.sh
  doc/configuration.rst
  setup.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/recommender.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_recommender.py
  sphinx_gallery/tests/tinybuild/doc/Makefile
  sphinx_gallery/tests/tinybuild/doc/conf.py
Labels: enhancement

#1230 DOC Put configuration list under headings
  doc/configuration.rst
Labels: documentation

#1232 MAINT Version 0.15.0 and changelog
  CHANGES.rst
  sphinx_gallery/__init__.py
Labels: maintenance

#1234 MAINT Bump version and update `maintainers.rst`
  doc/maintainers.rst
  sphinx_gallery/__init__.py
Labels: maintenance

#1236 MAINT: Fix deployment
  .circleci/docs_deploy.sh
Labels: maintenance

#1237 DOC: Fix formatting in contribute.rst
  doc/contribute.rst
Labels: documentation
