Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2023-10, with the labels that each got.

#1192 ENH: Support source files in any language
  doc/configuration.rst
  doc/reference.rst
  doc/syntax.rst
  sphinx_gallery/backreferences.py
  sphinx_gallery/block_parser.py
  sphinx_gallery/downloads.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/interactive_example.py
  sphinx_gallery/notebook.py
  sphinx_gallery/py_source_parser.py
  sphinx_gallery/tests/test_block_parser.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_gen_rst.py
  sphinx_gallery/tests/test_notebook.py
  sphinx_gallery/tests/test_utils.py
  sphinx_gallery/tests/tinybuild/doc/conf.py
  sphinx_gallery/tests/tinybuild/examples/isentropic.m
  sphinx_gallery/tests/tinybuild/examples/julia_sample.jl
  sphinx_gallery/tests/tinybuild/examples/parse_this.cpp
  sphinx_gallery/utils.py
Labels: enhancement

#1207 BUG: Fix bug with orphan sg_api_usage
  .github_changelog_generator
  .gitignore
  sphinx_gallery/gen_gallery.py
Labels: bug

#1213 FIX Copy JupyterLite contents early so it runs before jupyterlite_sphinx build-finished
  sphinx_gallery/gen_gallery.py
Labels: bug

#1216 MAINT: Improve CircleCI time
  .circleci/config.yml
  .circleci/setup_bash.sh
  .gitignore
Labels: maintenance

#1218 MAINT: pydata-sphinx-theme
  doc/conf.py
Labels: maintenance
