Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2023-09, with the labels that each got.

#1193 MAINT Fix check for mismatched "ignore" blocks
  sphinx_gallery/py_source_parser.py
  sphinx_gallery/tests/test_py_source_parser.py
Labels: bug

#1177 Avoid importing new modules in backrefs
  sphinx_gallery/backreferences.py
Labels: bug

#1197 ENH: Write all computation times
  .circleci/config.yml
  .github/workflows/circle_artifacts.yml
  .gitignore
  MANIFEST.in
  continuous_integration/azure/install.sh
  doc/Makefile
  doc/getting_started.rst
  setup.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/tinybuild/doc/Makefile
Labels: enhancement

#1199 DOC Note support for python 3.7 dropped in release notes
  CHANGES.rst
Labels: documentation

#1203 ENH: Improve API usage graph
  sphinx_gallery/gen_gallery.py
Labels: enhancement
