Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2023-08, with the labels that each got.

#1155 Maint: Fix `app.builder.outdir` as Sphinx now using pathlib
  sphinx_gallery/docs_resolv.py
  sphinx_gallery/tests/test_full.py
Labels: bug, maintenance

#1154 MAINT Update backreferences docs and add tests
  doc/configuration.rst
  sphinx_gallery/docs_resolv.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/tests/conftest.py
  sphinx_gallery/tests/test_backreferences.py
Labels: enhancement, maintenance

#1160 updated mpl gui warning catcher to new error message
  doc/configuration.rst
  sphinx_gallery/scrapers.py
  sphinx_gallery/tests/test_full.py
Labels: bug

#1166 MAINT: yamllint
  .github/workflows/main.yml
  .github/workflows/release.yml
  .pre-commit-config.yaml
  azure-pipelines.yml
  codecov.yml
Labels: maintenance

#1169 MAINT Fix lint, clean and expand docstrings
  doc/conf.py
  examples/plot_1_exp.py
  examples/plot_4_choose_thumbnail.py
  pyproject.toml
  sphinx_gallery/backreferences.py
  sphinx_gallery/directives.py
  sphinx_gallery/docs_resolv.py
  sphinx_gallery/downloads.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/interactive_example.py
  sphinx_gallery/load_style.py
  sphinx_gallery/notebook.py
  sphinx_gallery/py_source_parser.py
  sphinx_gallery/scrapers.py
  sphinx_gallery/sorting.py
  sphinx_gallery/tests/conftest.py
  sphinx_gallery/tests/test_backreferences.py
  sphinx_gallery/tests/test_docs_resolv.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_full_noexec.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/test_gen_rst.py
  sphinx_gallery/tests/test_interactive_example.py
  sphinx_gallery/tests/test_load_style.py
  sphinx_gallery/tests/test_notebook.py
  sphinx_gallery/tests/test_py_source_parser.py
  sphinx_gallery/tests/test_scrapers.py
  sphinx_gallery/tests/test_sorting.py
  sphinx_gallery/tests/test_utils.py
  sphinx_gallery/tests/tinybuild/doc/conf.py
  sphinx_gallery/tests/tinybuild/examples/local_module.py
  sphinx_gallery/tests/tinybuild/examples/plot_pickle.py
  sphinx_gallery/tests/tinybuild/examples/plot_repr.py
  sphinx_gallery/utils.py
Labels: maintenance

#1181 DOC Fix Jupyterlite config example in `configuration.rst`
  doc/configuration.rst
Labels: documentation

#1180 MAINT Add to `test_identify_names` so class property tested
  sphinx_gallery/tests/conftest.py
  sphinx_gallery/tests/test_backreferences.py
Labels: maintenance

#1172 MAINT Remove unused parametrize in `test_figure_rst_srcset`
  sphinx_gallery/tests/test_scrapers.py
Labels: maintenance

#1179 MAINT Lint - fix ast node type in docstrings
  sphinx_gallery/backreferences.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/py_source_parser.py
Labels: maintenance

#1173 MAINT Move `figure_rst` path testing to own unit test
  sphinx_gallery/tests/test_scrapers.py
Labels: maintenance

#1183 MAINT: Force PRs to be labeled properly
  .github/workflows/circle_artifacts.yml
  .github/workflows/label-check.yml
Labels: maintenance

#1184 MAINT: Release 0.14.0
  CHANGES.rst
  doc/maintainers.rst
  sphinx_gallery/__init__.py
Labels: maintenance

#1185 MAINT: Bump ver
  sphinx_gallery/__init__.py
Labels: maintenance
