Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2024-10, with the labels that each got.

#1383 Fix `indexst` variable does not exist when own index gallery is first
  doc/configuration.rst
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/tests/conftest.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/test_gen_rst.py
Labels: bug

#1385 Allow to disable writing computation times
  doc/configuration.rst
  sphinx_gallery/gen_gallery.py
Labels: enhancement

#1384 [ENH] Add option to render multiple images from same cell as single-img
  doc/configuration.rst
  examples/plot_1_exp.py
  examples/plot_9_multi_image_separate.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/scrapers.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_scrapers.py
  sphinx_gallery/tests/tinybuild/examples/plot_multi_image_block_separate.py
  sphinx_gallery/tests/tinybuild/examples/plot_multi_image_separate.py
Labels: enhancement

#1388 Release 0.18.0
  CHANGES.rst
  sphinx_gallery/__init__.py
Labels: maintenance

#1398 Add block-level `sphinx_gallery_capture_repr_block` setting
  .github/workflows/tests.yml
  doc/configuration.rst
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_gen_rst.py
Labels: enhancement
