Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2024-01, with the labels that each got.

#1247 Add HyperSpy and kikuchipy to 'who uses'
  README.rst
Labels: documentation

#1226 [ENH] Minigallery can take arbitrary files/glob patterns as input
  .github/workflows/tests.yml
  continuous_integration/install.sh
  dev-requirements.txt
  doc/configuration.rst
  doc/utils.rst
  sphinx_gallery/backreferences.py
  sphinx_gallery/directives.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/sorting.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_sorting.py
  sphinx_gallery/tests/tinybuild/doc/conf.py
  sphinx_gallery/tests/tinybuild/doc/make.bat
  sphinx_gallery/tests/tinybuild/doc/minigallery.rst
Labels: enhancement

#1253 ENH: minigallery_sort_order on full path
  doc/configuration.rst
  doc/utils.rst
  sphinx_gallery/directives.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/tinybuild/doc/conf.py
Labels: bug

#1255 fix: Missing full stop in download message
  sphinx_gallery/gen_rst.py
Labels: documentation
