Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2024-04, with the labels that each got.

#1278 Remove leftover config checking of `image_srcset`
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/tests/test_scrapers.py
Labels: maintenance

#1281 DOC Clarify sub level example gallery
  doc/configuration.rst
Labels: documentation

#1280 DOC Mention `image_srcset` config in scraper section in `advanced.rst`
  doc/advanced.rst
  doc/configuration.rst
Labels: documentation

#1287 Fix typo in `test_fileno`
  sphinx_gallery/tests/test_gen_rst.py
Labels: maintenance

#1292 DOC Update FFMpeg note in conf animation docs
  doc/configuration.rst
Labels: documentation

#1291 readme: adding quickstart section
  README.rst
Labels: documentation

#1289 BUG: Fix serialization with Sphinx 7.3
  .circleci/config.yml
  .github/install.sh
  .pre-commit-config.yaml
  CHANGES.rst
  dev-requirements.txt
  doc/advanced.rst
  doc/conf.py
  doc/configuration.rst
  doc/sphinxext/sg_doc_build.py
  sphinx_gallery/backreferences.py
  sphinx_gallery/directives.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/interactive_example.py
  sphinx_gallery/scrapers.py
  sphinx_gallery/tests/conftest.py
  sphinx_gallery/tests/test_backreferences.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/test_gen_rst.py
  sphinx_gallery/tests/test_notebook.py
  sphinx_gallery/tests/test_scrapers.py
  sphinx_gallery/tests/tinybuild/doc/conf.py
  sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py
  sphinx_gallery/tests/tinybuild/utils.py
Labels: bug

#1295 ENH: Allow plain list as subsection_order and support a wildcard
  doc/configuration.rst
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/sorting.py
  sphinx_gallery/tests/test_sorting.py
Labels: enhancement

#1296 MAINT version 0.16
  CHANGES.rst
  sphinx_gallery/__init__.py
Labels: maintenance

#1297 MAINT Bump version 0.17
  sphinx_gallery/__init__.py
Labels: maintenance

#1298 lint: define codespell in `pyproject.toml`
  MANIFEST.in
  ignore_words.txt
  pyproject.toml
Labels: maintenance

#1243 Allow setting animation format from gallery config
  .circleci/config.yml
  .circleci/setup_bash.sh
  .github/install.sh
  .github/workflows/tests.yml
  doc/configuration.rst
  pyproject.toml
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/scrapers.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/tinybuild/doc/conf.py
Labels: enhancement
