Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2024-07, with the labels that each got.

#877 ENH: Parallel gallery generation
  .circleci/config.yml
  .github/workflows/tests.yml
  CHANGES.rst
  doc/conf.py
  doc/configuration.rst
  doc/getting_started.rst
  doc/sphinxext/sg_doc_build.py
  pyproject.toml
  sphinx_gallery/backreferences.py
  sphinx_gallery/docs_resolv.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/interactive_example.py
  sphinx_gallery/py_source_parser.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/test_gen_rst.py
  sphinx_gallery/tests/tinybuild/doc/conf.py
  sphinx_gallery/utils.py
Labels: enhancement

#1346 DOC Add napari to users
  README.rst
  sphinx_gallery/tests/test_full.py
Labels: documentation

#1344 Introduction tooltip corresponds to the first paragraph
  sphinx_gallery/_static/sg_gallery.css
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_gen_rst.py
Labels: enhancement

#1347 MNT: Fix `gallery_conf` changes do not need to be returned
  sphinx_gallery/gen_gallery.py
Labels: maintenance

#1313 [ENH] Add custom thumbnails for failing examples
  doc/conf.py
  doc/configuration.rst
  examples/no_output/plot_raise_thumbnail.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_gen_rst.py
  sphinx_gallery/tests/tinybuild/doc/_static_nonstandard/broken_example.png
  sphinx_gallery/tests/tinybuild/doc/conf.py
  sphinx_gallery/tests/tinybuild/examples/plot_failing_example.py
  sphinx_gallery/tests/tinybuild/examples/plot_failing_example_thumbnail.py
Labels: enhancement

#1349 MNT: Release 0.17.0
  CHANGES.rst
  sphinx_gallery/__init__.py
Labels: maintenance

#1350 MNT Bump version
  sphinx_gallery/__init__.py
Labels: maintenance

#1352 Update pyvista in doc CI
  .circleci/config.yml
Labels: maintenance

#1353 FIX generate zipfiles when index passed by user
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/tests/test_full.py
Labels: bug

#1355 FIX Allow str path minigallery entries when backreferences off
  doc/configuration.rst
  sphinx_gallery/directives.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/testconfs/src/plot_1.py
Labels: bug

#1358 DOC Minor update to minigallery directive doc
  doc/configuration.rst
Labels: documentation
