Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2024-05, with the labels that each got.

#1301 BUG: Fix bug with traceback with SyntaxError
  doc/conf.py
  sphinx_gallery/docs_resolv.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_docs_resolv.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/test_gen_rst.py
Labels: bug

#1305 MAINT Add `sphinxcontrib-video` to dev requirements
  dev-requirements.txt
  doc/contribute.rst
Labels: maintenance

#1303 MNT: Turn the block tuple into a namedtuple
  doc/advanced.rst
  sphinx_gallery/backreferences.py
  sphinx_gallery/block_parser.py
  sphinx_gallery/directives.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/py_source_parser.py
  sphinx_gallery/recommender.py
  sphinx_gallery/scrapers.py
  sphinx_gallery/sorting.py
  sphinx_gallery/tests/test_backreferences.py
  sphinx_gallery/tests/test_gen_rst.py
  sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py
Labels: maintenance

#1299 add option for zip downloads
  sphinx_gallery/downloads.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/utils.py
Labels: enhancement

#1312 ENH integrate download/launcher links into `pydata-sphinx-theme` secondary sidebar
  MANIFEST.in
  doc/_static/hide_links.css
  doc/advanced.rst
  doc/conf.py
  sphinx_gallery/_static/sg_gallery.css
  sphinx_gallery/components/sg_download_links.html
  sphinx_gallery/components/sg_launcher_links.html
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/tinybuild/doc/conf.py
Labels: enhancement
