Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2024-06, with the labels that each got.

#1317 Include dev dependencies in pyproject.toml and update docs on requirements
  .github/install.sh
  MANIFEST.in
  README.rst
  dev-requirements.txt
  doc/contribute.rst
  doc/maintainers.rst
  pyproject.toml
Labels: maintenance

#1318 DOC: Remove definition lists from contribution guide
  doc/contribute.rst
Labels: documentation

#1320 Fix handling of multi-module intersphinx registries
  sphinx_gallery/docs_resolv.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py
Labels: bug

#1321 MNT: Rename README.rst to GALLERY_HEADER.rst
  MANIFEST.in
  doc/configuration.rst
  doc/getting_started.rst
  examples/GALLERY_HEADER.rst
  examples/no_output/GALLERY_HEADER.rst
  plotly_examples/GALLERY_HEADER.rst
  pyvista_examples/GALLERY_HEADER.rst
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/conftest.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/test_gen_rst.py
  sphinx_gallery/tests/testconfs/src/GALLERY_HEADER.rst
  sphinx_gallery/tests/tinybuild/doc/conf.py
  sphinx_gallery/tests/tinybuild/doc/index.rst
  sphinx_gallery/tests/tinybuild/examples/GALLERY_HEADER.rst
  sphinx_gallery/tests/tinybuild/examples_README_header/README.txt
  sphinx_gallery/tests/tinybuild/examples_README_header/plot_exp.py
  sphinx_gallery/tests/tinybuild/examples_with_rst/GALLERY_HEADER.rst
  tutorials/README.txt
Labels: enhancement

#1329 MNT: Add ipython to dev dependencies
  pyproject.toml
Labels: maintenance

#1327 Fix make file clean in tinybuild
  sphinx_gallery/tests/tinybuild/doc/Makefile
Labels: maintenance

#1333 MNT Use `os.sep` everywhere
  sphinx_gallery/backreferences.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/interactive_example.py
Labels: maintenance

#1334 MNT: Refactor `_fill_gallery_conf_defaults`
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/test_scrapers.py
Labels: maintenance

#1335 MNT: Refactor `generate_file_rst`
  sphinx_gallery/gen_rst.py
Labels: maintenance

#1332 MNT: Refactor `generate_dir_rst` and `generate_gallery_rst`
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/utils.py
Labels: maintenance

#1336 FIX Jupyterlite in CircleCI artifact
  sphinx_gallery/interactive_example.py
  sphinx_gallery/tests/test_interactive_example.py
Labels: enhancement

#1337 MNT: Sort imports and add to pre commit
  .pre-commit-config.yaml
  doc/conf.py
  examples/no_output/plot_raise.py
  examples/plot_0_sin.py
  examples/plot_1_exp.py
  examples/plot_2_seaborn.py
  examples/plot_4_choose_thumbnail.py
  examples/plot_4b_provide_thumbnail.py
  examples/plot_5_unicode_everywhere.py
  examples/plot_6_function_identifier.py
  examples/plot_8_animations.py
  plotly_examples/plot_0_plotly.py
  pyvista_examples/plot_collisions.py
  sphinx_gallery/backreferences.py
  sphinx_gallery/block_parser.py
  sphinx_gallery/directives.py
  sphinx_gallery/docs_resolv.py
  sphinx_gallery/downloads.py
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/interactive_example.py
  sphinx_gallery/notebook.py
  sphinx_gallery/py_source_parser.py
  sphinx_gallery/recommender.py
  sphinx_gallery/scrapers.py
  sphinx_gallery/tests/conftest.py
  sphinx_gallery/tests/test_backreferences.py
  sphinx_gallery/tests/test_block_parser.py
  sphinx_gallery/tests/test_docs_resolv.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/test_full_noexec.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/test_gen_rst.py
  sphinx_gallery/tests/test_interactive_example.py
  sphinx_gallery/tests/test_load_style.py
  sphinx_gallery/tests/test_notebook.py
  sphinx_gallery/tests/test_py_source_parser.py
  sphinx_gallery/tests/test_scrapers.py
  sphinx_gallery/tests/test_sorting.py
  sphinx_gallery/tests/tinybuild/doc/conf.py
  sphinx_gallery/tests/tinybuild/examples/future/plot_future_imports.py
  sphinx_gallery/tests/tinybuild/examples/plot_animation.py
  sphinx_gallery/tests/tinybuild/examples/plot_command_line_args.py
  sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py
  sphinx_gallery/tests/tinybuild/examples/plot_pickle.py
  sphinx_gallery/tests/tinybuild/examples/plot_second_future_imports.py
  sphinx_gallery/tests/tinybuild/examples/plot_svg.py
  sphinx_gallery/tests/tinybuild/examples_README_header/plot_exp.py
  sphinx_gallery/tests/tinybuild/examples_rst_index/examp_subdir1/plot_sub1.py
  sphinx_gallery/tests/tinybuild/examples_rst_index/examp_subdir2/plot_sub2.py
  sphinx_gallery/tests/tinybuild/examples_rst_index/plot_examp.py
  sphinx_gallery/tests/tinybuild/examples_with_rst/plot_boo.py
  sphinx_gallery/tests/tinybuild/examples_with_rst/plot_cos.py
  sphinx_gallery/tests/tinybuild/utils.py
  sphinx_gallery/utils.py
Labels: maintenance

#1339 DOC Fix nested_sections
  doc/configuration.rst
Labels: documentation
