Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2024-11, with the labels that each got.

#1399 BUG: make _anim_rst windows compatible
  sphinx_gallery/scrapers.py
Labels: bug

#1391 Fix custom sort
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/testconfs/src/first-subsection/GALLERY_HEADER.rst
  sphinx_gallery/tests/testconfs/src/first-subsection/plot_4.py
  sphinx_gallery/tests/testconfs/src/first-subsection/plot_5.py
  sphinx_gallery/tests/testconfs/src/first-subsection/plot_6.py
  sphinx_gallery/tests/testconfs/src/second-subsection/GALLERY_HEADER.rst
  sphinx_gallery/tests/testconfs/src/second-subsection/plot_7.py
  sphinx_gallery/tests/testconfs/src/second-subsection/plot_8.py
  sphinx_gallery/tests/testconfs/src/second-subsection/plot_9.py
  sphinx_gallery/tests/tinybuild/doc/conf.py
  sphinx_gallery/utils.py
Labels: bug

#1402 MNT Add test for `minigallery_sort_order`
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/utils.py
Labels: maintenance

#1401 DOC Improve custom sort key docs
  doc/configuration.rst
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_gen_gallery.py
Labels: documentation
