Repository sphinx-gallery/sphinx-gallery, pull requests merged in 2024-08, with the labels that each got.

#1361 MNT Add warning when 'examples_dirs' and 'gallery_dirs' unequal lengths
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/tests/test_gen_gallery.py
Labels: maintenance

#1363 Fix linking to class attributes with prefer_full_module
  sphinx_gallery/docs_resolv.py
Labels: bug

#1362 DOC add note on filtering joblib warnings
  doc/configuration.rst
Labels: documentation

#1360 Improve minigallery directive path input resolution
  pyproject.toml
  sphinx_gallery/directives.py
  sphinx_gallery/tests/conftest.py
  sphinx_gallery/tests/test_gen_gallery.py
Labels: bug

#1365 MNT Change mark and fixture names for adding files
  pyproject.toml
  sphinx_gallery/tests/conftest.py
  sphinx_gallery/tests/test_gen_gallery.py
  sphinx_gallery/tests/test_load_style.py
Labels: maintenance

#1364 Obey prefer_full_module setting when finding backreferences
  sphinx_gallery/_dummy/__init__.py
  sphinx_gallery/_dummy/nested.py
  sphinx_gallery/backreferences.py
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/conftest.py
  sphinx_gallery/tests/test_backreferences.py
  sphinx_gallery/tests/test_full.py
  sphinx_gallery/tests/tinybuild/doc/conf.py
  sphinx_gallery/tests/tinybuild/doc/index.rst
  sphinx_gallery/tests/tinybuild/examples/plot_numpy_matplotlib.py
Labels: bug

#1366 ENH: Improve _sanitize_rst
  sphinx_gallery/gen_rst.py
  sphinx_gallery/tests/test_backreferences.py
Labels: bug

#1367 DOC Improve doc about joblib warnings
  doc/configuration.rst
Labels: documentation

#1369 FIX: Fix stability of stored compiled regex
  sphinx_gallery/gen_gallery.py
  sphinx_gallery/gen_rst.py
Labels: bug

#1370 Release 0.17.1
  CHANGES.rst
  sphinx_gallery/__init__.py
Labels: maintenance
